services:
  flask-app:
    build: ./flask-app
    ports:
      - "4900:5000"
    environment:
      - FLASK_ENV=production
    restart: always

  apache:
    image: httpd:2.4
    ports:
      - "80:80"
    volumes:
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
    depends_on:
      - flask-app